### ISSUE TITLE
Step Template Structure

### ISSUE THREAD

**Issue by JCapriotti** [OctopusDeploy/Library#100]
I started working on a step template and got stuck on the recommended article: http://www.lavinski.me/making-great-octopus-powershell-step-templates/

I like the idea of testing the script outside of Octopus and providing parameter validation, but struggled a bit. In a nutshell:
* I didn't want to define my parameters in three different spots in my script
* I found a few problems specifying required parameters, then I noticed the basic script at the bottom doesn't work (run it without parameters and it doesn't throw an error).

So assuming I'm not missing anything, I created a function for testing. It sets up $OctopusParameters and then calls a tweaked/shortened version of the blog's example. See [my Gist for an example](https://gist.github.com/JCapriotti/45639e06ba777ee974b1).

I plan to create a pull request for my step when it is finished. If there is interest in adopting this style of testing, I was curious if there is a place I could through that script.

**Comment by alfhenrik** [comment]
Hi @JCapriotti,

Thanks for the excellent example in your gist. I've updated the README to include a link to it.
