### ISSUE TITLE
Environment Variable in SSIS on SQL server unchecked after deployment

### ISSUE THREAD

**Issue by jamal136** [OctopusDeploy/Library#1021]
---

### Step template
Deploy ISPAC SSIS project from Referenced Package

### Step template parameter inputs

![Ispac template](https://user-images.githubusercontent.com/70285126/96456436-63ed2b00-1216-11eb-954d-e256a716ed00.png)

![Environment checkbox](https://user-images.githubusercontent.com/70285126/96456467-6f405680-1216-11eb-93e6-20cff28101d6.png)

### Step template version
Latest

### Step template related environment information
On Prem SQL Server 2016, all SSIS Pre-req loaded and working

### Octopus Server version
V 2020.4.0

### Expected behavior

The environment checkbox should be ticked on, otherwise CD does not work

### Actual behavior

The checkbox is unchecked and an error prompt is visible

### Possible solution
_If you might have an idea of what the issue is, please let us know_

### Steps to reproduce the problem (for bugs)
Create an environment within SSIS package and deploy.
_If there are specific steps that you took when you encountered the bug, please list them here_

**Comment by twerthi** [comment]
Greetings @jamal136 !  I want to make sure I understand what you're reporting.  Are you indicating that the Use Environment checkbox should be checked by default?  Or is there something else going on?

**Comment by twerthi** [comment]
I think I'm following now.  It's coupled with the environment name, so the original design was to make it flexible.  Checking it in the template allows it to work correctly, yes?

**Comment by jamal136** [comment]
If you mean the powershell template, then I have set to TRUE the “Reference project (and package) parameters to environment variables “ but still doesn’t work.

On 19 Oct 2020, at 16:03, Shawn Sesna <notifications@github.com> wrote:

﻿

I think I'm following now. It's coupled with the environment name, so the original design was to make it flexible. Checking it in the template allows it to work correctly, yes?

**Comment by twerthi** [comment]
Oh!  You're reporting that despite checking the boxes, it's not setting it up correctly?  As in they're not mapped?

**Comment by jamal136** [comment]
Effectively it should check this box by way of the template config variables but it doesn’t. Therefore I have to manually check this on for it to work.

[cid:3F2190F0-C527-4A84-A174-A50EB55D2353-L0-001]

Sent from my iPhone

On 19 Oct 2020, at 16:10, Shawn Sesna <notifications@github.com> wrote:

﻿

Oh! You're reporting that despite checking the boxes, it's not setting it up correctly? As in they're not mapped?

**Comment by twerthi** [comment]
Let me know if you have time for a call, I think I'm following, but it might be easier to show me :)

**Comment by jamal136** [comment]
sure thing, what’s the best number?

Sent from my iPhone

On 19 Oct 2020, at 16:31, Shawn Sesna <notifications@github.com> wrote:

﻿

Let me know if you have time for a call, I think I'm following, but it might be easier to show me :)

**Comment by twerthi** [comment]
I'm in a meeting at the moment, I'll send a zoom link once I'm out.

**Comment by jamal136** [comment]
ok thanks

Sent from my iPhone

On 19 Oct 2020, at 16:38, Shawn Sesna <notifications@github.com> wrote:

﻿

I'm in a meeting at the moment, I'll send a zoom link once I'm out.

**Comment by twerthi** [comment]
https://octopus.zoom.us/j/92273123202?pwd=NUZpa2VVWDN2QUhSUW41WisyR1hndz09

**Comment by jamal136** [comment]
Ta, I’m on

Sent from my iPhone

On 19 Oct 2020, at 17:21, Shawn Sesna <notifications@github.com> wrote:

﻿

https://octopus.zoom.us/j/92273123202?pwd=NUZpa2VVWDN2QUhSUW41WisyR1hndz09

**Comment by twerthi** [comment]
Nice to meet you :)  If you feel this is resolved, please close this issue :)

**Comment by jamal136** [comment]
Nice meeting you too. Big thanks for your help.
