### ISSUE TITLE
[question] provide examples for Variable Substitute in Files

### ISSUE THREAD

**Issue by lmayorga1980** [OctopusDeploy/Library#109]
Can someone provide a working example with the following Script Template?

https://library.octopusdeploy.com/#!/step-template/actiontemplate-variables-substitute-in-files

Thanks.

**Comment by alfhenrik** [comment]
So very, very sorry for not giving this attention until now!

It may no longer be required, but I've provided a working example below of how to set this step template up.

Again, my apologies for not getting to this sooner than I did, I am very sorry!

Thanks,
Henrik

### Working example for anyone that needs it

Folder with some files:
![image](https://cloud.githubusercontent.com/assets/1035315/11555956/7a4a75aa-99ef-11e5-8884-a970583c1c27.png)

Contents of those files:
![image](https://cloud.githubusercontent.com/assets/1035315/11556270/55db7ff0-99f1-11e5-8af7-c2bfb0475984.png)

Step in project:
![image](https://cloud.githubusercontent.com/assets/1035315/11556067/21652092-99f0-11e5-9518-6dc5fa7dd4e8.png)

Project variables:
![image](https://cloud.githubusercontent.com/assets/1035315/11556073/2c7c40dc-99f0-11e5-92c1-146cbde73265.png)

Log from deployment:
```
Getting target files...
19:02:46Info
	Found 2 file(s)
19:02:46Info
Will use Octostache.dll (TentacleVersion 3.2.1)
19:02:46Info
Looking for Octostache.dll...
19:02:46Info
Loading from C:\Octopus\Calamari\3.1.17\Octostache.dll
19:02:46Info
Loading template file C:\Temp\VariableSubstitution\app.json...
19:02:46Info
	Read 100 bytes
19:02:46Info
Loading $OctopusParameters...
19:02:46Info
Resolving variables...
19:02:46Info
Writing the resolved template to C:\Temp\VariableSubstitution\app.json
19:02:46Info
Done!
19:02:46Info
Looking for Octostache.dll...
19:02:46Info
Loading from C:\Octopus\Calamari\3.1.17\Octostache.dll
19:02:46Info
Loading template file C:\Temp\VariableSubstitution\web.foo.json...
19:02:46Info
	Read 106 bytes
19:02:46Info
Loading $OctopusParameters...
19:02:46Info
Resolving variables...
19:02:46Info
Writing the resolved template to C:\Temp\VariableSubstitution\web.foo.json
19:02:46Info
Done!
```

File contents post-deployment:
![image](https://cloud.githubusercontent.com/assets/1035315/11556221/ffb71a26-99f0-11e5-8b9e-e25b5f05e7bb.png)
