### ISSUE TITLE
Automated tests for Step-Templates?

### ISSUE THREAD

**Issue by joshbtn** [OctopusDeploy/Library#113]
Are there currently automated tests for Step templates?

**Comment by JCapriotti** [comment]
I don't think there are. However, I think I am going to start adding some. I have a pending pull requests (well, one with several updates) so hopefully if we start making unit tests, they will be easier to accept.

My idea is to use Pester and some sort of wrapper to call the step template JSON.

**Comment by josh3ennett** [comment]
Nice, I haven't heard of pester before.  It looks like the right tool for the job.  I might take some time looking into this approach as well, let me know if you come up with anything. I agree It could help speed up acceptance of these site templates.

**Comment by JCapriotti** [comment]
I haven't used Pester myself, but it seems to be pretty popular. 

I have a slow start on a test for IIS app creation... nothing worth seeing. But in thinking about the test code, I've settled on writing more of a functional test as opposed to a unit test. Most of the Pester examples have a lot of mock setup, which I can see getting pretty unruly. I'd rather test that the step works than focus on a specific method being called.

**Comment by alfhenrik** [comment]
At some point I'd like to have a way to testing the step templates so that these tests can be run as part of our CI build when a PR is submitted.

Once I have some free time, I will sit down and spike a way to do these tests. For now I will close this issue.

**Comment by alfhenrik** [comment]
Reopening this so that I have a way to track it. (silly of me to close the issue at all really)

**Comment by dragon788** [comment]
This guy has some great comments on testing Octopus Step Templates. http://www.lavinski.me/making-great-octopus-powershell-step-templates/

**Comment by matt-richardson** [comment]
Here's another approach http://mjrichardson.com/blog/continuous-integration-with-octopus-deploy-step-templates/ that I have used with success previously.

**Comment by dragon788** [comment]
@matt-richardson That's awesome! I think I'd run across ASOS at some point, but the style and testability is fantastic.

**Comment by matt-richardson** [comment]
> but the style and testability is fantastic.
Credit to @paulmarsy here. Before he got to it, it was just a plain old `build.ps` :)

**Comment by DevOpsDerek** [comment]
Closing as no comment in 4 years.
