### ISSUE TITLE
Unable to install Kubernetes - Create Service Account and Target step template

### ISSUE THREAD

**Issue by jmezach** [OctopusDeploy/Library#1139]
---

### Step template
Kubernetes - Create Service Account and Target

### Step template parameter inputs
I'm unable to install the Step Template into my Octopus Cloud instance so I don't even get this far

### Step template version
Version 11

### Step template related environment information
Nothing specific afaik

### Octopus Server version
Octopus Cloud

### Expected behavior
I expect the Step Template to install into my Octopus Cloud instance

### Actual behavior
I get an error when I click on the Install button:

```
There was a problem with your request.
Please select a control type for parameter 'CreateK8sTargetContainerImageFeed'.
Please select a control type for parameter 'CreateK8sTargetContainerImage'.
```

### Possible solution
Looking at the step template it seems that no control type is specified for those parameters. Unfortunately I'm not sure what it should be.

### Steps to reproduce the problem (for bugs)
1. Log into a Octopus Cloud instance
2. Go to Library -> Step Templates
3. Click Browse Library
4. Find the Kubernetes - Create Service Account and Target and click Install
5. Click Save
6. I receive the error

**Comment by harrisonmeister** [comment]
Hey @jmezach 

Thanks for raising this issue, I've pushed a fix that should make the community library in the next 30 mins or so.

Once it's there you can sync your instance using the **Sync Now** button under **Configuration -> Features** to get the new version (version 12)

![image](https://user-images.githubusercontent.com/1418993/124935728-d51b7b00-dffd-11eb-9749-c64d666afce3.png)

**Comment by harrisonmeister** [comment]
The change should be in the library now

**Comment by jmezach** [comment]
@harrisonmeister Thanks for the quick action. I can confirm that I'm now able to install the template.

**Comment by harrisonmeister** [comment]
> @harrisonmeister Thanks for the quick action. I can confirm that I'm now able to install the template.

That's great. Thanks for confirming!
