### ISSUE TITLE
[Feature Request] Annotations on K8s namespace

### ISSUE THREAD

**Issue by jmezach** [OctopusDeploy/Library#1140]
Not sure if this is the right place, but I figured I'd post an issue here first since I would like to propose a new feature for the Kubernetes - Create Service Account and Target step template. We are in the process of setting up our Kubernetes cluster so that we can deploy to it using Octopus Deploy. We're trying to adopt some of the best practices as outlined in [this recent blog post](https://octopus.com/blog/10-pillars-kubernetes-deployments) which suggests using this Step Template to create Kubernetes namespaces and associated service accounts for the various environments. This seems like a good idea to do.

In our case we use the same Kubernetes cluster for dev/test/production, but we have worker nodes that are in two different networks to separate between dev/test and production. We've looked at using the PodNodeSelector admission controller so that we can annotate the namespaces with the appropriate node selector so that pods end up on the right workers automatically. Unfortunately the step template currently doesn't allow specifying annotations when the namespace is being created.

This seems like an easy enough feature to add and I'd be more than willing to send a PR for it, but I wanted to discuss whether this is a good idea first. I'm thinking of adding a multi-line text input parameter to the step template in which one could specify key=value pairs of annotations that would then be added to the namespace.

**Comment by harrisonmeister** [comment]
Hi @jmezach - thanks for the feedback. I've passed it on internally, I'll keep this open for now (in case they want to respond) :+1:

**Comment by mcasperson** [comment]
That sounds like a reasonable addition to the template. Given all the inputs available to a step template, a multiline text box with many line separated key=value pairs would also be my choice.

I wonder though if a more generic solution would be to provide a text box that holds an inline kustomize.yaml file might be more flexible. That way any of the resources created by this template could be modified in any way.

Would kustomize provide a solution for your use case @jmezach?

**Comment by jmezach** [comment]
I don't have a lot of experience with Kustomize so I'll have to dig into that. Looks like it is integrated into `kubectl` nowadays though, so yeah, I think it will work for my scenario.
