### ISSUE TITLE
Chain Deployment step template fails to create a new release of a project

### ISSUE THREAD

**Issue by srigor** [OctopusDeploy/Library#1171]
### Step template
Octopus Chain Deployment

### Step template parameter inputs
![image](https://user-images.githubusercontent.com/6719052/131411154-39357dde-66f1-4b87-876a-f3313c3c559d.png)

### Step template version
23

### Octopus Server version
2021.1

### Expected behavior

Process step should successfully create a release of the chain project

### Actual behavior

Process step fails with
17:38:41   Verbose  |       Error Response:
17:38:41   Verbose  |       {
17:38:41   Verbose  |       "ErrorMessage": "The resource you requested was not found."
17:38:41   Verbose  |       }

### Possible solution
The issue appears to be at this line:
`$this.Channel = Invoke-OctopusApi $this.Project.Links.Channels | % Items | ? { $useDefaultChannel -and $_.IsDefault -or $_.Name -eq $channelName }`

Project.Links.Channels returns something like this for a project with a single, default channel:
> /octo/api/Spaces-1/projects/Projects-2397/channels{?skip,take,partialName}

Which causes the Invoke-OctopusApi function's $requestParameters.Uri to have "octo" in it twice because the $Chain_BaseUrl and the $Uri both have /octo in it:
`Uri = ('{0}/{1}' -f $Chain_BaseUrl, $Uri.TrimStart('/'))`
> http://octopus.my-company.com/octo/octo/api/Spaces-1/projects/Projects-2397/channels

This faulty endpoint resolves to a 404 Not Found.

**Comment by srigor** [comment]
I can workaround this issue by forking the Chain Deployment step template and changing the setting of the $requestParameters.Uri within the Invoke-OctopusApi function to remove the duplicate "octo" reference:
`Uri = ('{0}/{1}' -f $Chain_BaseUrl, $Uri.TrimStart('/')) -replace '\/octo\/octo\/','/octo/`

But I'd prefer to not have to fork the template if possible.

**Comment by harrisonmeister** [comment]
Hi @srigor 

Thanks for getting in touch, and sorry to hear about the issue you're having. To help us understand where the issue may be, can you confirm the following:

- The value of the variable `Octopus.Web.BaseUrl` for your instance.
- The value of the variable `Octopus.Web.ServerUri` for your instance.
- Whether or not you have set the setting for the step: `Octopus.Action.OctopusServerUrl` in a project or library variable set variable. This value will:
 > override the base url used for all webrequests, making it possible to chain deployments on a different Octopus instance/server, or as a workaround for misconfigured node settings

Obviously feel free to mask the real address, we're just curious about whether or not a virtual style directory is being used called `octo` :) 

Thanks!

**Comment by harrisonmeister** [comment]
Hey @srigor 

I raised a PR for the chain deployment step, hoping it will get merged today or tomorrow :+1:

**Comment by harrisonmeister** [comment]
https://github.com/OctopusDeploy/Library/pull/1179 should fix this issue (which has now been merged).

**Comment by srigor** [comment]
@harrisonmeister Thanks for getting a fix out for this so quickly. I updated to the latest version of the Chain Deployment step template and tested it; it works beautifully!

**Comment by harrisonmeister** [comment]
> @harrisonmeister Thanks for getting a fix out for this so quickly. I updated to the latest version of the Chain Deployment step template and tested it; it works beautifully!

Hey @srigor - that's great to hear. Thanks for raising it. This helps to make the step template work for more use-cases :tada:
