### ISSUE TITLE
Step templates from PowerShell DSC modules

### ISSUE THREAD

**Issue by Tadas** [OctopusDeploy/Library#122]
Hi,

I'm working on a PS script that generates step templates from DSC modules. I think it might be useful to someone but I didn't find any info on how to contribute something other than a step template. Any suggestions?

**Comment by alfhenrik** [comment]
Yea, we don't currently have a way to contribute anything other than step templates here. Perhaps in the future we will expand the library to include other things that could be useful for users of Octopus.
