### ISSUE TITLE
Azure Logo

### ISSUE THREAD

**Issue by weeyin83** [OctopusDeploy/Library#1264]
The Azure logo that is shown when you get to the "Choose Step Template" page is out of date.  
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/13692824/169029831-bd23ca70-a2fe-4a16-9f42-fd075224c8b0.png">

Is it possible to start using the new Azure logo?

![azure](https://user-images.githubusercontent.com/13692824/169032265-e1ddb2ca-810c-4015-b45a-ce8008fd98cd.svg)

**Comment by harrisonmeister** [comment]
@weeyin83 - this is controlled inside Octopus Server itself and not the Community Library application :smile:
