### ISSUE TITLE
GCP Secret Manager - Retrieve Secrets - Add option to ignore warning when retrieving latest version of secret

### ISSUE THREAD

**Issue by bryanroth** [OctopusDeploy/Library#1353]
### Step template
GCP Secret Manager - Retrieve Secrets

### Step template parameter inputs
Secret names to retrieve should reference "latest" of the secret being retrieved:
![image](https://user-images.githubusercontent.com/183269/235194823-5528d267-31c8-40fd-9e98-3359d5817f66.png)

### Step template version
Version 2 (latest)

### Step template related environment information
N/A

### Octopus Server version
v2023.2 (Build 5011-hotfix.7619)

### Expected behavior
Have the option to not display a warning when retrieving the latest version of a secret. There are legitimate use cases when you would want to get the latest version of a secret instead of specifying the version number, e.g. if a secret gets a new version regularly (password rotation).

### Actual behavior
A warning is written to output: _Retrieving the 'latest' version for secret isn't recommended. Consider choosing a specific version to retrieve._

This marks deployments or runbook runs with the warning symbol which is not desired.

### Possible solution
Add a parameter (checkbox) to the step template to bypass the warning that is displayed when retrieving the `latest` version for a secret. This checkbox can be set to `false` (unchecked) by default.

![image](https://user-images.githubusercontent.com/183269/235197424-3e191652-d379-4741-a3c4-4c8de1a5fda9.png)

![image](https://user-images.githubusercontent.com/183269/235197709-bb3a79bc-477b-4fa3-a6d4-e7495e11af2c.png)

### Steps to reproduce the problem (for bugs)
N/A

**Comment by harrisonmeister** [comment]
Hey @bryanroth 

Thanks for raising the issue. I see the use-case for not wanting a warning there. I think it's easier if I downgrade the warning to a `Write-Host` so I've put a PR in for that.

**Comment by harrisonmeister** [comment]
Version 3 of the template should now be available. It may take a few hours for your Octopus instance to update, or you can download the new change from the configuration -> features menu
