### ISSUE TITLE
Command Timeout parameter has no effect in SQL - Deploy DACPAC using SqlPackage step template

### ISSUE THREAD

**Issue by JonathanKeav** [OctopusDeploy/Library#1366]
### Step template
SQL - Deploy DACPAC using SqlPackage

### Step template parameter inputs
DACPACPackageName: i_conX.Database.dacpac
Publish profile file name: i_conX.Database.publish.xml
Report: True
Script: True
Deploy: False
Target Servername: #{DatabaseServerName}
Target Database: #{DatabaseName}
Authentication type: Windows Integrated
Username: #{MSAUsername}
Password: ********
DACPAC Package: Package i_conX.Database from feed Octopus Server (built-in)
Command Timeout: 12000
SqlPackage executable location: c:\sqlpackage\sqlpackage.exe
Additional arguments:

### Step template version
latest

### Octopus Server version
2023.1.9788

### Expected behavior
step pass successfully

### Actual behavior
step failed with below error
Executing the following command: sqlpackage /SourceFile:"F:\Octopus\Work\20230530160919-77973-12\DACPACPackage\i_conX.Database.dacpac" /TargetConnectionString:"Application Name=OctopusDeploy;Server=XSSQL01;Trusted_Connection=True;Initial Catalog=BASE.Staging;TrustServerCertificate=true;" /Profile:"F:\Octopus\Work\20230530160919-77973-12\DACPACPackage\i_conX.Database.publish.xml" /OutputPath:F:\Octopus\Work\20230530160919-77973-12\DACPACPackage/reports/XSSQL01.BASE.Staging.20230530160924.DeployReport.xml /Action:DeployReport 
Generating report for database 'BASE.Staging' on server 'XSSQL01'. 
Time elapsed 0:11:49.83 
*** An error occurred during deployment plan generation. Deployment cannot continue. 
Failed to import target model BASE.Staging. Detailed message Unable to reconnect to database: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. 
Unable to reconnect to database: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. 
Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. 
The wait operation timed out. 
Microsoft.PowerShell.Commands.WriteErrorException: Execution failed! 
NotSpecified: Execution failed! 
At F:\Octopus\Work\20230530160919-77973-12\Script.ps1:519 char:9 
+         Invoke-SqlPackage -Action "DeployReport" -Arguments ($sqlPack ... 
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
at Invoke-SqlPackage, F:\Octopus\Work\20230530160919-77973-12\Script.ps1: line 402 
at <ScriptBlock>, F:\Octopus\Work\20230530160919-77973-12\Script.ps1: line 519 
at <ScriptBlock>, <No file>: line 1 
at <ScriptBlock>, F:\Octopus\Work\20230530160919-77973-12\Octopus.FunctionAppenderContext.ps1: line 211 
at <ScriptBlock>, F:\Octopus\Work\20230530160919-77973-12\Bootstrap.Octopus.FunctionAppenderContext.ps1: line 5050 
at <ScriptBlock>, <No file>: line 1 
at <ScriptBlock>, <No file>: line 1 
May 30th 2023 17:21:22Fatal
The remote script failed with exit code 1 
May 30th 2023 17:21:22Fatal
The action SQL - View DACPAC using SqlPackage on XSSQL01 failed

### Possible solution
Wire up value of #{DACPACCommandTimeout} variable to be used by SqlPaclage.exe. I tried this myself but couldn't get it to work.

### Steps to reproduce the problem (for bugs)
Use SQL - Deploy DACPAC using SqlPackage step ato upgrade databse with a large amount of tables (circa 300K) such that the default command timeout is reached - which looks to be 10 mins given "Time elapsed 0:11:49.83" in error above

**Comment by twerthi** [comment]
@JonathanKeav , Thank you for brining this to our attention.  I'll see if I can take a look.

**Comment by twerthi** [comment]
@JonathanKeav I investigated the template and found I completely missed that variable and it indeed does nothing.  I have developed a fix for it.  In the meantime, you can workaround it by adding `/Properties:CommandTimeout=<number>` to the `Additional arguments` section and it should work until the fix is published.
