### ISSUE TITLE
Issue with Run Azure DevOps Build Pipeline

### ISSUE THREAD

**Issue by delphe** [OctopusDeploy/Library#1418]
### Step template

Run Azure DevOps Build Pipeline

### Step version

1

### Octopus version

2023.2.12643

### Step template parameter inputs

Azure DevOps Wait Until Completion = False

### What happened

An error message showed up and the step was marked as failed.

### Reproduction steps

Set "Azure DevOps Wait Until Completion" param to False and run the deployment

### More Information

If we are not waiting for the pipeline to complete we shouldn't check the status. I changed the last part of the PowerShell script to the following to resolve the issue:
`else 
{
   Write-Host "Azure DevOps pipeline status unknown. Update process to wait until completion for status updates."
}`

**Comment by twerthi** [comment]
@delphe It looks like you may have solved this, would you be able to submit the change to the template?

**Comment by delphe** [comment]
> @delphe It looks like you may have solved this, would you be able to submit the change to the template?

Yes. Please see https://github.com/OctopusDeploy/Library/pull/1420
