### ISSUE TITLE
Slack - Send Simple Notification cannot create SSL connection

### ISSUE THREAD

**Issue by AlexAtEF** [OctopusDeploy/Library#1459]
### Step template

Slack - Send Simple Notification 

### Step version

15

### Octopus version

2020.5.1

### Step template parameter inputs

Nothing special here.
![image](https://github.com/OctopusDeploy/Library/assets/112872820/770963fc-6bf6-45b5-821b-8ace4db19943)

### What happened

We receive the following error:
```
InvalidOperation: The request was aborted: Could not create SSL/TLS secure channel. 
December 4th 2023 10:30:47Error
At D:\Octopus\Work\20231204093025-275682-59\Script.ps1:24 char:9 
December 4th 2023 10:30:47Error
+         Invoke-Restmethod -Method POST -Body ($payload | ConvertTo-Js ... 
December 4th 2023 10:30:47Error
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
December 4th 2023 10:30:47Error
at <ScriptBlock>, D:\Octopus\Work\20231204093025-275682-59\Script.ps1: line 24 
December 4th 2023 10:30:47Error
at <ScriptBlock>, <No file>: line 1 
December 4th 2023 10:30:47Error
at <ScriptBlock>, D:\Octopus\Work\20231204093025-275682-59\Octopus.FunctionAppenderContext.ps1: line 177 
December 4th 2023 10:30:47Error
at <ScriptBlock>, D:\Octopus\Work\20231204093025-275682-59\Bootstrap.Octopus.FunctionAppenderContext.ps1: line 10454 
December 4th 2023 10:30:47Error
at <ScriptBlock>, <No file>: line 1 
December 4th 2023 10:30:47Error
at <ScriptBlock>, <No file>: line 1 
An error occurred while attempting to send Slack notification 
December 4th 2023 10:30:47Info
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel. 
December 4th 2023 10:30:47Info
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request) 
December 4th 2023 10:30:47Info
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord() 
December 4th 2023 10:30:47Info
The request was aborted: Could not create SSL/TLS secure channel. 
December 4th 2023 10:30:47Error
The remote script failed with exit code 1 
December 4th 2023 10:32:34Info
Guidance received: Ignore 
```

### Reproduction steps

Run step with valid parameters.

### More Information

This step was working well as of our last run (10/31), but didn't work this time.

We run it on the Octopus Server itself.

**Comment by twerthi** [comment]
Greetings!  May I ask what version of the template you're using?

**Comment by AlexAtEF** [comment]
Hi! We're using version 15, which seems to be the latest. I see it has the `SecurityProtocol` TLS 1.2 configuration, but we're still getting this error.

**Comment by twerthi** [comment]
The line 
```
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls11 -bor [System.Net.SecurityProtocolType]::Tls12
```
Will attempt to do 1.2, but fall back if it cannot.  This _sounds_ like it could be the server isn't configured to use 1.2.  What version of the OS is your Octopus server running?  Would it be possible to use a worker instead of the server itself to see if that helps?

**Comment by nstrom-tn** [comment]
FWIW we're running into this issue as well as of last week, happened w no configuration changes on our end. I'm guessing Slack changed something w/ their TLS acceptance settings. Octopus v2019.12.1 LTS, template version 15 ("Detailed Notification" step in our case but I'm sure the same holds for both). I don't think running on a worker will be viable since we'll get duplicate notifications when deploying to multiple targets.

**Comment by twerthi** [comment]
I've run a few tests and cannot reproduce the issue, I'm using samples.octopus.app.  My guess is I'm missing something to properly reproduce.  Are you able to run something like [IISCrypto](https://www.nartac.com/Products/IISCrypto) to verify that TLS settings are configured?

@nstrom-tn I'm not sure I'm following what you mean by running on a worker would duplicate notifications, would you be able to elaborate?  It should be just switching it from executing directly on the server to a worker.

**Comment by nstrom-tn** [comment]
I don't have access to the octopus server itself so can't really troubleshoot further, I'm just a user here at my org.

**Comment by twerthi** [comment]
@nstrom-tn Ah!  Thank you for that clarification.  Based on that screenshot, you're correct, however, the step should be able to run on a worker and your selection should look like this, does it not?

![image](https://github.com/OctopusDeploy/Library/assets/5552453/d7169a7e-e81c-4aaa-ae9f-83b75a76b298)
****

**Comment by twerthi** [comment]
@nstrom-tn Ah, okay.  I found a [blog post](https://manage.accuwebhosting.com/knowledgebase/3578/How-to-enable-TLS-1-2-on-Windows-2012-Server.html) on how to enable TLS 1.2 on Windows 2012, this might help your situation.

**Comment by AlexAtEF** [comment]
I am in the same boat - running octopus v2020.5.1 on Windows Server 2012. It seems the root of the problem is that  Windows 2012 doesn't have the right SSL cyphers.

```PORT    STATE SERVICE
443/tcp open  https
|_ssl-date: TLS randomness does not represent time
| ssl-cert: Subject: commonName=slack.com
| Subject Alternative Name: DNS:*.slack.com, DNS:slack.com
| Issuer: commonName=R3/organizationName=Let's Encrypt/countryName=US
| Public Key type: rsa
| Public Key bits: 2048
| Signature Algorithm: sha256WithRSAEncryption
| Not valid before: 2023-11-17T03:18:30
| Not valid after:  2024-02-15T03:18:29
| MD5:   258d 85bd b803 6377 0d21 6eb3 6b0b 87ae
|_SHA-1: ec64 ac7c 8233 8879 dd4f 14eb 217c 77f7 d3f8 8fb2
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|     compressors: 
|       NULL
|     cipher preference: client
|   TLSv1.3: 
|     ciphers: 
|       TLS_AKE_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_AKE_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|     cipher preference: client
|_  least strength: A```

So it seems the solution is to run the action on a newer target that can be narrowed to a single instance or update octopus to allow for the `Run once on a worker` option.
