### ISSUE TITLE
Azure Cli Issue with Azure Administer WebJob

### ISSUE THREAD

**Issue by sharmaharry** [OctopusDeploy/Library#1516]
### Step template

Azure Administer WebJob

### What happened

How to update this template to use Azure Cli rather than octopus cli as the steps come up with warnings

### Reproduction steps

Create a web job using above template

**Comment by twerthi** [comment]
It looks like this template was based off of a deprecated step which didn't include the ability to switch where the tools are loaded.  It would be best to create a new template using the `Run an Azure Script` and copy the script and parameters into the new template.

**Comment by sharmaharry** [comment]
what a coincidence, I did the same a few hours before you posted this. Thanks a lot for publishing this anyways

**Comment by twerthi** [comment]
Nice!  Were you going to submit it to the Library?

**Comment by sharmaharry** [comment]
yes I have awaiting PR review for merge

**Comment by sharmaharry** [comment]
created new template
