### ISSUE TITLE
Amazon S3 Upload bug (doesn't support nested folders)

### ISSUE THREAD

**Issue by phillip-haydon** [OctopusDeploy/Library#229]
https://github.com/OctopusDeploy/Library/blob/master/step-templates/amazon-s3-upload.json

I'm terrible at powershell and have been trying for hours to fix this.

The script doesn't support nested folders. Only the first level of folders.

So:

```
./
./test.css
./folder/test.css
./folder/child/test.css
```

Results in S3 recieving:

```
./
./test.css
./folder/test.css
```

Where the folder child is ignored.

**Comment by alfhenrik** [comment]
Hi @phillip-haydon,

Thanks for reporting this issue, while we get this fixed and deployed to the production site you can modify the following line in the `Upload` function:

```
foreach ($i in Get-ChildItem $item)
```

to 

```
foreach ($i in Get-ChildItem $item -Recurse)
```

Cheers,
Henrik

**Comment by phillip-haydon** [comment]
Hey, I tried that and it resulted in all files being uploaded to the root of the bucket. So everything was taken from the child directories and put in the root.

**Comment by alfhenrik** [comment]
@phillip-haydon were you able to get this working in the end? If not, I'll get an environment setup to test it myself and get a fix put in for it.
