### ISSUE TITLE
Variables - Substitute in Files

### ISSUE THREAD

**Issue by shadab12** [OctopusDeploy/Library#232]
Hi,
We using Octopus version 2.6.5.1010, and in the C:\Octopus\Applications\.SQ-TWSYDSV633-1FF6A2BC\Octopus.Tentacle\2.6.5.1010\Octopus.Platform.dll' I can see the Octopus.Platform.dll but I'm getting the below error. Can anyone help?

Add-Type : Could not load file or assembly 'file:///C:\Octopus\Applications\.SQ-TWSYDSV633-1FF6A2BC\Octopus.Tentacle\2.6.5.1010\Octopus.Platform.dll' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.

At C:\Users\sabiztalkdev\AppData\Local\Tentacle\Temp\a8924e8f-3e75-474e-aea8-42

+ Add-Type <<<<  -Path ($OctopusParameters['Octopus.Tentacle.Agent.ProgramDirecoryPath'] + "\Octopus.Platform.dll")
    + CategoryInfo          : NotSpecified: (:) [Add-Type], BadImageFormatException

    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.AddTypeCommand

Info    09:09:04
==============================================
PowerShell exit code: 1
==============================================

Fatal    09:09:04
PowerShell script returned a non-zero exit code: 1
Tentacle version 2.6.5.1010

**Comment by alfhenrik** [comment]
@shadab12 what operating system is your Tentacle running on? It looks like the PowerShell session is loading an earlier version of .NET (my guess would be that the Tentacle is starting a PS2.0 session which by default loads the .NET 2.0 CLR), hence the `This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.`

If this is the case, a workaround would be to upgrade the PS to 3.0 on your Tentacle server.
