### ISSUE TITLE
SSRS step template error - Cannot find LoadReportDefinition method

### ISSUE THREAD

**Issue by jeremyhoughton** [OctopusDeploy/Library#261]
Hi,

We have been trying to use the step template to deploy SSRS reports and shared datasets found here: https://library.octopusdeploy.com/#!/step-template/actiontemplate-deploy-ssrs-reports-from-a-package

One problem we are getting is that the following piece of code which is located in the Update-ReportParameters function is failing:

```
$ExecutionInfo = $ReportExecutionProxy.LoadReportDefinition($ReportData, [ref] $ReportExecutionWarnings);
```

For some reason it can't find the method LoadReportDefinition on the $ReportExecutionProxy object. We have stepped through it using Powershell ISE and the method doesn't even appear in the  code autocomplete. Is there any work around for this or maybe a missing namespace?

**Comment by alfhenrik** [comment]
@twerthi is this something you know how to solve quickly? 

If not, I'll get an environment setup and figure out what's happening here.

**Comment by twerthi** [comment]
What version of PowerShell are they using?

**Comment by jeremyhoughton** [comment]
@twerthi please see the answers to your questions below. Please let me know if you need anymore information?

**Powershell Version:**
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.18449
BuildVersion                   6.2.9200.16628
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2

**SQL Server Reporting Services Version:**
Microsoft SQL Server Reporting Services Version 11.0.3000.0

**$ReportExecutionProxy:**
Yes $ReportExecutionProxy has a value. In the template it is initiated like so:
```$ReportExecutionProxy = New-WebServiceProxy -Uri $ReportExecutionUrl -UseDefaultCredential```

Where $ReportExecutionUrl = *"http://xxxxx/ReportServer/ReportService2005.asmx?wsdl"* via the template parameter

We actually get autocomplete on $ReportExecutionProxy through the Powershell ISE, however the method LoadReportDefinition does not seem to be there?

$ReportExecutionProxy.GetType() returns *Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1er_ReportService2005_asmx_wsdl.ReportingService2005*

**Comment by twerthi** [comment]
The value for $ReportExecutionUrl should look like this: 

http://<server>/reportserver/ReportExecution2005.asmx?wsdl

The value you've supplied here is what would be for the $ReportServiceUrl

**Comment by jeremyhoughton** [comment]
Thanks @twerthi. It works fine now! Maybe it might be worth while putting some error checking in the code to either check for the text "ReportExecution" in the input execution report url or to check whether that url has access to the LoadReportDefinition method? If there is an error raise an exception early suggesting that the input url is invalid?

**Comment by twerthi** [comment]
Not a bad idea, I'll look into that.
