### ISSUE TITLE
iis-change-app-offline-online.json is incorrect

### ISSUE THREAD

**Issue by mmiller678** [OctopusDeploy/Library#265]
I think the variable are declared incorrectly and the logic is flawed.  The last if statement that removes the offline html doesn't make sense to me. If your taking the application offline why would you remove the existing offline file? I think instead the logic should be used when your moving the application online. If both the online and offline files exists - just remove the offline file. I attached what I think is the correct approach.

[export.txt](https://github.com/OctopusDeploy/Library/files/57025/export.txt)

**Comment by alfhenrik** [comment]
@mmiller678 thanks for reporting this issue, and my apologies this didn't get caught in the review process!

I'll update the step template and get it deployed to production as soon as possible.
