### ISSUE TITLE
Enable 32bit applications always resolving to true

### ISSUE THREAD

**Issue by awworrell** [OctopusDeploy/Library#268]
When creating application pools on the servers, we have unchecked the box to install as a 32 bit application. Once the app pool is created, it is set to a 32 bit application. I have also modified the default value of the parameter to be equal to false. When I create a new release and deploy, the pool is still created as a 32 bit application. I am testing on my side to figure out how to create the pool as a 65 bit pool. Could someone look into this also?

**Comment by alfhenrik** [comment]
Hi @awworrell, thanks for getting in touch, I assume this is the [step template](http://library.octopusdeploy.com/#!/step-template/actiontemplate-iis-apppool-create) you are using?

I've tested this step template in one of my environments with the checkbox unchecked and the AppPool was created to not enable 32-bit applications, see below:

![image](https://cloud.githubusercontent.com/assets/1035315/11968657/465d6156-a95a-11e5-8fe5-bf971800b0c3.png)

Is this not the result you are seeing when using this step template?

Thanks!

**Comment by awworrell** [comment]
Hey alfhenrik. That is the step template i am using. When looking at this with the system administrators, that value is set to x86 not true or false. When i try to set it directly via the step template, it stays as x86. Would you happen to know how to change that value? I may need to ask them to try manually modifying it on the server.

**Comment by awworrell** [comment]
Hey alfhenrik. I spoke with the system admin again this morning. I re-ran the default template and this is what I got from it. I also found that I was incorrect about it being x86. It was set to true. By default on the server side it is set to false.
![snipimage](https://cloud.githubusercontent.com/assets/14314073/12024020/7bf511a6-ad65-11e5-8dbc-8a0f2368c847.JPG)

**Comment by dragon788** [comment]
@awworrell did you happen to pull and import the latest version of the template when you ran it the last time? One of the things I have been missing is the ability to get notified if there is a newer version of a step template I imported through the Octopus Deploy UI.

**Comment by rbonestell** [comment]
I want to set certain application pools for specific deployments to `Enable 32-bit Applications` = `True` but I can't figure out how to do so using the OctopusDeploy-provided step template. How are you getting it to do so above?

**Comment by alfhenrik** [comment]
@rbonestell using this [step template](https://library.octopusdeploy.com/step-templates/70a293d6-ee6a-4755-8e06-5f13d7e51fff/actiontemplate-iis-apppool-create) you should be able to enable that by making sure the checkbox is checked as below:

![image](https://cloud.githubusercontent.com/assets/1035315/21912634/ed446160-d972-11e6-9c00-66622bc1f80a.png)

Does this not work for you or am I misinterpreting your question?

**Comment by rbonestell** [comment]
@alfhenrik Thanks!
I've installed that step template and implemented it, I didn't realize it would update already-existing Application Pools as well. This does exactly what I need to set my idleTimeout and enable32BitOnWin64!

**Comment by alfhenrik** [comment]
I'm not able to replicate the initial issue, so I'm going to close this issue for now, but if someone is still having issues with it not working as it should please let me know and I'll re-open the issue and investigate further.
