### ISSUE TITLE
update a step?

### ISSUE THREAD

**Issue by ironfist** [OctopusDeploy/Library#322]
i have been using the SQL Database Backup step for quite a while in several projects. Now I see there's an update (I'm on v5 and the one here is v6). How do I update (re-import) my step in Octopus Deploy without having to re-add the step to all my projects? 

I know I can change the Powershell script manually but I want to re-import so I know I'm getting the changes represented here.

Thx

**Comment by alfhenrik** [comment]
Hey @ironfist, 

Sorry for the delay in replying to you, I've create a [gist](https://gist.github.com/alfhenrik/be0b2f1694b68ec893ea9e031e84b210) that shows how to update a step template to the latest version.

I hope that helps!
