### ISSUE TITLE
Author names missing

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Library#354]
Hi folks! Just noticed that the authors of several step templates no longer seem to be appearing:

![image](https://cloud.githubusercontent.com/assets/342712/17385653/79902d82-5a27-11e6-9f05-63c39c28ae73.png)

I'm on Chrome/Win10.

**Comment by matt-richardson** [comment]
It appears that those templates don't have a LastModifiedField, which is where [it reads the author](https://github.com/OctopusDeploy/Library/blob/master/app/services/LibraryDb.js#L39) details.

Looks like we need to add a test to the build process to ensure this is set correctly.

**Comment by alfhenrik** [comment]
Yea, this is due to a change we made to how we audit things in Octopus where we removed the `LastModifiedBy` and `LastModifiedAt` from our documents.

Adding a test would be a good solution to pick up when these fields are missing.
