### ISSUE TITLE
Notify of updates to external step templates from the Octopus Library in the local Library view

### ISSUE THREAD

**Issue by dragon788** [OctopusDeploy/Library#359]
One of the things I have been missing is the ability to get notified if there is a newer version of a step template I imported through the Octopus Deploy UI. This means that when I made local changes to a template that I want to contribute back, I don't know how old the local copy was and I may be munging and overwriting other useful changes that would be better to merge (and all the metadata in the files makes it hard to merge as well).

**Comment by dragon788** [comment]
@PaulStovell Would this be better tracked under the Octopus Server repository?

**Comment by alfhenrik** [comment]
@dragon788 this is part of an upcoming new feature in Octopus where we will redesign the way that we integrate with the community library.
