### ISSUE TITLE
Many things are broken in IE11

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Library#374]
Having  downloaded and tested the library on a Win7 - IE11 (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) machine. It appears as though the `Copy to clipboard` button does not work on IE.

Based on the 3rd party [react-copy-to-clipboard](https://github.com/nkbt/react-copy-to-clipboard) library used it appears that this should work on IE11. Testing their demo page (http://nkbt.github.io/react-copy-to-clipboard/) indeed shows that in theory this should be working.

**Comment by alfhenrik** [comment]
Also the `Show JSON` and `Show script` links

**Comment by alfhenrik** [comment]
Searching is also broken...I'm just gonna conclude that **most** things seems broken in IE11

**Comment by DevOpsDerek** [comment]
Closing as no comment in 4 years.
