### ISSUE TITLE
Previous deployment step dropdown also contains current step 

### ISSUE THREAD

**Issue by Grendizr** [OctopusDeploy/Library#381]
Discovered a bug in v3.4.4 ... 

Within step template, step parameter of control type  "Previous deployment step name" should display only previous steps.
But when used within a process, parameter dropdown contains all previous step names including current step which is a bit odd.

Can use this dummy template to reproduce
`{
  "Id": "ActionTemplates-3",
  "Name": "FixMe :)",
  "Description": "Previous step parameter contains current step which is wrong",
  "ActionType": "Octopus.Script",
  "Version": 0,
  "Properties": {
    "Octopus.Action.Script.Syntax": "PowerShell",
    "Octopus.Action.Script.ScriptSource": "Inline",
    "Octopus.Action.RunOnServer": "false",
    "Octopus.Action.Script.ScriptBody": "Write-Host \"fix me !!\"",
    "Octopus.Action.Script.ScriptFileName": null,
    "Octopus.Action.Package.FeedId": null,
    "Octopus.Action.Package.PackageId": null
  },
  "Parameters": [
    {
      "Id": "c6626a1d-9cf6-4c8c-886f-e0d6bfb166ff",
      "Name": "PreviousStep",
      "Label": "Should only display previous steps",
      "HelpText": null,
      "DefaultValue": null,
      "DisplaySettings": {
        "Octopus.ControlType": "StepName"
      }
    }
  ],
  "$Meta": {
    "ExportedAt": "2016-09-20T07:50:42.563Z",
    "OctopusVersion": "3.4.4",
    "Type": "ActionTemplate"
  }
}`

**Comment by alfhenrik** [comment]
This has been fixed in Octopus (issue was not related to the community library step templates)
