### ISSUE TITLE
Create Scheduled Task/No password

### ISSUE THREAD

**Issue by veccsolutions** [OctopusDeploy/Library#471]
When creating a scheduled task with no password (running as the System user) it will fail because it can't validate the argument list. The fix I found was to check if the password field was empty, if it was, don't include the password parameter.

Changing line 21 from
```
    $argumentList += @( "/RP", $RunAsPassword );
```
to
```
    if( -not (StringIsNullOrWhiteSpace($RunAsPassword)))
    {
        $argumentList += @( "/RP", $RunAsPassword );
    }
```

**Comment by alfhenrik** [comment]
Fixed in #481
