### ISSUE TITLE
Windows-Scheduled-Task-Disable doesn't work

### ISSUE THREAD

**Issue by veccsolutions** [OctopusDeploy/Library#486]
The last commit of the windows-scheduled-task changed all of the \" to \\\" which results in a \" in the script where there should only be a ". I could easily create a pull request with the fix.

**Comment by veccsolutions** [comment]
Github removed the additional backslashes that were supposed to be there.

`
The last commit of the windows-scheduled-task changed all of the \" to \\\" which results in a \" in the script where there should only be a ". I could easily create a pull request with the fix.
`

**Comment by jaymickey** [comment]
> I could easily create a pull request with the fix.

Then you should!

**Comment by alfhenrik** [comment]
Fixed in https://github.com/OctopusDeploy/Library/issues/497
