### ISSUE TITLE
Scoping of variable in community step templates should be mandatory

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Library#556]
Currently there are no guidelines to make sure community step templates authors "scope" their variable names used in the step template.
This can lead with clashed with existing variable defined in scopes that take precedence.

**Comment by stagor** [comment]
Hi @johnsimons thanks for lodging this issue. I would suggest to use dedicated dictionary that is referencing step template's arguments like **$StepArguments["_parameter-name_"]**
