### ISSUE TITLE
chain deployment step template incorrectly interprets links urls

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Library#560]
It seems the `Links` urls are template based and https://github.com/OctopusDeploy/Library/blob/master/step-templates/octopus-chain-deployment.json is not interpreting those links before consuming them.

Issue raise in http://help.octopusdeploy.com/discussions/problems/55833

**Comment by Bullseye4486** [comment]
To fix this, I think you can just add 

$Uri = $Uri -replace '{.*?}',''

to the beginning of the Invoke-OctopusApi function.

**Comment by alfhenrik** [comment]
Hi @robertglickman,

Would you be interested in sending a Pull Request with your proposed fix for this issue? If not, that's totally OK and I'll get to it as soon as I can.

Thanks,
Henrik

**Comment by hullscotty1986** [comment]
Hi @alfhenrik,

Thanks for doing the merge. How long does it take octopus to recognise the new version? Under my usage tab it still says version 14 and up to date. Can I force it to update somehow?

Thanks

Scott

**Comment by alfhenrik** [comment]
You can force a sync by going to `Configuration->Features` and clicking the `Sync now` button in the `Octopus Community Step Templates` section. IIRC we only run that sync once per day (and on server startup)
