### ISSUE TITLE
File System - Clean Directory: Expressions are only allowed as the first element of a pipeline exception

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Library#588]
This [change](https://github.com/OctopusDeploy/Library/commit/a692c6aa09f3767af654b554b1a35bf18cff652a) is now causing an "Expressions are only allowed as the first element of a pipeline" exception due to the $exclude = $exclude | {$_} assignment.

**Comment by TrevorPilley** [comment]
+1 I'm getting the same error.
