### ISSUE TITLE
Step template client side support

### ISSUE THREAD

**Issue by rpooley** [OctopusDeploy/Library#613]
### Step template
None, this is a suggestion for Octopus Deploy client side support.

### Step template parameter inputs
I would expect the step template to take a URL much like the custom template HTTP - Invoke URL

### Step template version
None

### Step template related environment information
None

### Octopus Server version
3.13.3

### Expected behavior
I would like to supply a URL in the step that would open a new tab with that URL loaded.
When we deploy there are a number of addresses we like to check first before proceeding, at the moment we have to put them in the Manual Intervention step and copy and paste them into a browser one by one which surprisingly takes some time. Client side access for steps would enable us to do a simple javascript window open. I know this may have it's risks but it would sure help.

### Actual behavior
None

### Possible solution
None

### Steps to reproduce the problem (for bugs)
None

**Comment by ryanrousseau** [comment]
Hi @rpooley,

In newer versions of Octopus, you can use the Write-Highlight commandlet to add clickable links to your deployment logs.

```powershell
Write-Highlight "Updated site: [Site Name](https://siteurl)"
```

Best,
Ryan
