### ISSUE TITLE
Slack Server Error Causes Build Failure

### ISSUE THREAD

**Issue by traviswatsonws** [OctopusDeploy/Library#626]
### Step template
Slack - Send Simple Notification
https://github.com/OctopusDeploy/Library/blob/master/step-templates/slack-send-simple-notification.json

### Step template parameter inputs
Any configuration will replicate

### Step template version
Version 7

### Step template related environment information
No requirements

### Octopus Server version
3.12.8

### Expected behavior

Continue on error

### Actual behavior

Build failure causing a full rollback

### Possible solution
Either swallow Slack failures entirely, or add an option to swallow them.  Could also create a retry.

### Description
While Slack is typically reliable, occasionally service errors do happen.  This step does not handle them gracefully.  Instead, it causes a step failure, and since Octopus cannot currently be configured to ignore step errors, it causes a full deployment rollback.

For build failures, this may be acceptable, since your build is already failed.  But in other cases, it's not.  In our case it was actually notifying of a _successful_ deploy, so ironically, this step rolled back a deploy that was complete, and successful.

![image](https://user-images.githubusercontent.com/835300/34219840-249be22a-e578-11e7-9930-cae11f758f77.png)

**Comment by DevOpsDerek** [comment]
Closing as no update in 3 years.
