### ISSUE TITLE
Chain Deployment gives 403 forbidden error with REL 2018.5

### ISSUE THREAD

**Issue by ChrisSharpeNZ** [OctopusDeploy/Library#687]
---

### Step template
Chain Deployment
https://library.octopus.com/step-templates/18392835-d50e-4ce9-9065-8e15a3c30954

### Step template parameter inputs
All of our usages are failing in the same way without change, but I have chaindeploy01.png and chaindeploy02.png which illustrate a very basic one. Default settings, just using a variable to name another project which it is calling.
![chaindeploy01](https://user-images.githubusercontent.com/19794713/40690170-cc2a3bfe-63f9-11e8-8072-dd70cb7cbf83.png)
![chaindeploy02](https://user-images.githubusercontent.com/19794713/40690171-cc7d10a4-63f9-11e8-98fc-5467a40d16c1.png)

### Step template version
The latest commit by Robert Glickman. The comment in the step template reads:
15. July 17, 2017 - Robert Glickman @robertglickman
    - Fixed an issue where the step would fail in Octopus 3.15+ due to templated URIs not being handled

### Step template related environment information
N/A - this is project 1 calling project 2 through octopus.

### Octopus Server version
2018.5, we were happily running ChainDeploys on 2018.3

### Expected behavior
The ChainDeploy should succesfully call the second project.

### Actual behavior
Deployed in Octopus with full logging turned on. the 403 error is repeated, and then eventually fails the step.
![deploy01](https://user-images.githubusercontent.com/19794713/40692273-ebc6a5b4-6404-11e8-949a-7dea944f89c8.png)
![deploy02](https://user-images.githubusercontent.com/19794713/40692272-eb86dede-6404-11e8-8ba4-8ff172f1c4e1.png)

### Possible solution
I'm not strong enough with .NET dev to understand the template fully, but I assume that the API call has some different parameters now in 2018.5 which stops the ChainDeploy call to retrieve the available releases. I created an API key with full permissions to everything in Octopus and it still supplied 403 forbidden.

### Steps to reproduce the problem (for bugs)
Make project A in octopus
Make Project B in octopus
Add a step template from A to call B
Run it and see this issue.

**Comment by robertglickman** [comment]
FWIW, we are using Octopus Server version 2018.5.1 and our Chain Deployment is still working as before. What happens when you visit the URL for your Octopus server /api/projects/all in your browser?

**Comment by ChrisSharpeNZ** [comment]
First thing it did was ask me for sign in, then after I signed in, and then
tried the url again it returned a big list of projects, including the one I
need.

**Comment by robertglickman** [comment]
I know this is not necessarily desirable for your case, but does it work if you create a new release rather than using an existing release? That's one difference between your configuration and ours. The only other thing I would recommend is double-checking the value of the API key.

**Comment by ChrisSharpeNZ** [comment]
Hi Robert,

I've tried that. Regardless of whether you use create new release or not, it fails at the retrieval step.
If you're getting past the RETRIEVE RELEASE step, then I'll mess around further with what is happening at that step.

**Comment by robertglickman** [comment]
I don't have a retrieve release step in mine. Only:

Creating Release
Configuring Deployment
Queue Deployment
Waiting For Deployment
Deployment Successful!

**Comment by ChrisSharpeNZ** [comment]
Hi Robert,

Can you confirm how you achieve a chaindeployment without the RETRIEVE RELEASE step?

Appreciate your help thus far

**Comment by robertglickman** [comment]
As far as I can tell, the only differences are that we have "Create new release" set to true and "Update Variable Snapshot" set to true

**Comment by ChrisSharpeNZ** [comment]
@robertglickman I was able to identify the issue with this, and it is indeed configuration on our side.

I will close this issue off, and appreciate your work on this.
