### ISSUE TITLE
Unable to update community step in Octopus Server

### ISSUE THREAD

**Issue by pregress** [OctopusDeploy/Library#715]
### Step template
https://github.com/OctopusDeploy/Library/blob/master/step-templates/azure-add-or-update-azure-loadbalancer-health-probe.json

### Step template parameter inputs
Doesn't matter for updating step templates

### Step template version
0

### Step template related environment information
/

### Octopus Server version
2018.8.4

### Expected behavior
I should be able to update the step template (the current version is 1)

### Actual behavior
No update link/button is displayed. I was able to update: https://github.com/OctopusDeploy/Library/blob/master/step-templates/azure-add-or-update-azure-loadbalancer-rule.json 

### Possible solution
/

### Steps to reproduce the problem (for bugs)
- Install the version 0 of the template
- Try to update it.

**Comment by DevOpsDerek** [comment]
Closing as no update in 2 years.
