### ISSUE TITLE
Template "IIS Application - Create" Intermittent Failures

### ISSUE THREAD

**Issue by bpape1** [OctopusDeploy/Library#722]
### Step template
IIS Application - Create

### Step template parameter inputs
See attached images (
![templateparams](https://user-images.githubusercontent.com/43546890/46368786-b6b31480-c646-11e8-9695-7f80295f03bf.png)
![templateparams2](https://user-images.githubusercontent.com/43546890/46368796-bca8f580-c646-11e8-9f59-1d0fa1d751e6.png).)

### Step template version
Version 36

### Step template related environment information
This is happening for IIS on Windows Server 2012 R2.
![iis](https://user-images.githubusercontent.com/43546890/46368807-c7fc2100-c646-11e8-9ba9-a9e896ac540b.png)

### Octopus Server version
Octopus v2018.8.1

### Expected behavior
Update/Create IIS Application.

### Actual behavior
Intermittent failures when running deployments.  Usually this will be successful on 1 server, but fail on the other.  The failures occur on both servers, not always the same server.  Rerunning the deployment for the tenant that failed will succeed.  See the attachments for error details (
[Exception.txt](https://github.com/OctopusDeploy/Library/files/2439199/Exception.txt).)
Sometimes these errors are related to other processes writing to the file (
[Exception2.txt](https://github.com/OctopusDeploy/Library/files/2439200/Exception2.txt).)

### Possible solution
I wish I could provide a possible solution, but I am not sure how this could be fixed.

### Steps to reproduce the problem (for bugs)
Create 25 process steps that run in parallel and use the IIS Application - Create step template to add an web application to a site in IIS (this would mimic our process.)
Run a deploy (may take a few to get the issue as it doesn't always happen.)

**Comment by DevOpsDerek** [comment]
Closing as no update in 2 years.
