### ISSUE TITLE
Adding a Chain Deploy step fails when trying to save it: 403

### ISSUE THREAD

**Issue by hermot** [OctopusDeploy/Library#728]
---

### Step template
Chain Deployment

### Step template parameter inputs
![image](https://user-images.githubusercontent.com/4687224/47081933-5efed680-d20c-11e8-83c5-02779c766b32.png)

![image](https://user-images.githubusercontent.com/4687224/47081962-72aa3d00-d20c-11e8-8a62-8578627964c1.png)

The rest are just default or blank.

### Step template version
Not sure where I can see the version

### Octopus Server version
v2018.8.2

### Expected behavior

The step should be save to the project

### Actual behavior

It fails to save the step and gives this error:

![image](https://user-images.githubusercontent.com/4687224/47081546-375b3e80-d20b-11e8-89b2-1ffd3dd0da64.png)

### Steps to reproduce the problem (for bugs)
Added this community step template to my project
Provided values
Try to save it

**Comment by DevOpsDerek** [comment]
Closing Issue as no update in a year
