### ISSUE TITLE
Template "HTTP - Test URL" parameter not considered in script body

### ISSUE THREAD

**Issue by Pietrowicz** [OctopusDeploy/Library#735]
### Step template
HTTP - Test URL (http-test-url.json)

### Step template parameter inputs
![image](https://user-images.githubusercontent.com/9408037/47506772-13ce6e80-d871-11e8-8e6d-f4b0533a910f.png)

### Step template version
14

### Expected behavior

Tieout would be applied according to the parameters value

### Actual behavior

Parameter "Timeout" is not used in script body

**Comment by hnrkndrssn** [comment]
Fixed in https://github.com/OctopusDeploy/Library/pull/736
