### ISSUE TITLE
Deployment of DACPAC Failing on Data Loss

### ISSUE THREAD

**Issue by MetalPaw** [OctopusDeploy/Library#741]
### Step template
SQL - Deploy DACPAC

### Step template parameter inputs
![image](https://user-images.githubusercontent.com/1525573/48395790-0a724c80-e721-11e8-977d-b65dfd3ab584.png)
![image](https://user-images.githubusercontent.com/1525573/48395818-1cec8600-e721-11e8-9b5d-ea44296e973f.png)

### Step template version
Version 11

### Octopus Server version
v2018.8.11

### Expected behavior
When using the "Additional deployment contributor arguments" BlockOnPossibleDataLoss set to false, i.e. /p:BlockOnPossibleDataLoss=false as would be used in a manual dacpac deploy, the deployment should allow for columns to be dropped, even if there are rows in the table.

### Actual behavior
This parameter seems to be ignored and the deployment fails due to the fact that there are rows in the table where I am trying to drop a column.

![image](https://user-images.githubusercontent.com/1525573/48396084-ecf1b280-e721-11e8-819c-6ae0b467d106.png)

### Possible solution
Ensure that the arguments are actually being included and that they are being included correctly.

### Steps to reproduce the problem (for bugs)
Take any working dacpac deployment step.
Add the above argument.
Change the dacpac to drop a column of a table that has rows.
Attempt to deploy the dacapac.

**Comment by CoderKooke** [comment]
We are having the same issue to Azure SQL ... did you resolve this @MetalPaw ?

**Comment by ced455** [comment]
Hello @DulaLoku  a lot of people are still seeking a way to use /p:BlockOnPossibleDataLoss in your octopus template.
Are you willing to edit your template to make it work or you do not support this step anymore ?

**Comment by DevOpsDerek** [comment]
Closing Issue as no update in a year

**Comment by Siliconrob** [comment]
Open this back up

**Comment by twerthi** [comment]
@Siliconrob, the recommended workaround for this is to use a publish profile https://www.mssqltips.com/sqlservertutorial/9007/define-a-publish-profile-for-ssdt/

As far as I can tell, the "Additional deployment contributor arguments" isn't meant for that particular option.  If I'm wrong, please provide a link to documentation as I haven't been able to find any.
