### ISSUE TITLE
Question: Multi OS Templates

### ISSUE THREAD

**Issue by Marcus-James-Adams** [OctopusDeploy/Library#803]
I notice a number of community templates at first appear as if they work on for Windows & Linux but then when you go to use then you find they are Windows / PowerShell only.  Eg file system related or zip

It kind of feels wrong to me to create a separate set of templates that duplicate window sonly ones for linux.......

So 

In theory, you could install PowerShell on the Linux nodes (i've not tried to see if this works) and this seems the simplest way.

or could you have a multi-script template that had properties options for both OS's or for each script type supported eg something like
  "Properties": {
      "Octopus.Action.Script.Syntax": "PowerShell", [
           "Octopus.Action.Script.ScriptSource": "Inline",
            "Octopus.Action.Script.ScriptBody": "write-host this is powershell"
      ]
      "Octopus.Action.Script.Syntax": "Bash", [
           "Octopus.Action.Script.ScriptSource": "Inline",
            "Octopus.Action.Script.ScriptBody": "echo this is in bash /r /n"
      ]
  },

**Comment by hnrkndrssn** [comment]
Hi @Marcus-James-Adams, 

Multi-script templates would require quite a substantial architectural refactor of the current way steps in Octopus works (it's also shared between built-in steps and step templates). But, we're about to introduce [PowerShell (Core) on Linux](https://github.com/OctopusDeploy/Issues/issues/5881) in Octopus so this might be the solution to your question. 🙂 

Cheers,
Henrik

**Comment by DevOpsDerek** [comment]
Closing Issue as no update in a year
