### ISSUE TITLE
Feature request: Ansible-Playbook (local) 

### ISSUE THREAD

**Issue by Marcus-James-Adams** [OctopusDeploy/Library#804]
Whilst there is an AnsibleTower community template this requires that you have purchased ansible tower.  Since Octopus can do most of the tower functions for you, it's expensive overkill.

However, having a template that took a playbook file and (optionally) a variables file (both being able to be entered inline ( with the usual variable & transform options) or form a repo then executing them on the target directly would be of benefit.

it would have to check if ansible was already installed on the target and if not install that first.  This would only work on Linux boxes.  Or perhaps it could be installed on the octopus deployment nodes ( using the new linux subsystem or cgywin) which would then allow you to run ansible scripts on both windows and linux boxes

**Comment by DevOpsDerek** [comment]
Closing Issue as no update in a year
