### ISSUE TITLE
Shared DataSet Issue with XML as DataSource

### ISSUE THREAD

**Issue by ankushparab** [OctopusDeploy/Library#828]
Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines.

This repository is a collection of community step templates where the majority of step templates were written by members of the Octopus Deploy community, not the Octopus team.

If you are reporting a bug with a specific step template, we'd really appreciate it if you could send a PR with a fix for the bug. 
If you want to send a PR but you're not sure how to create a PR, see GitHub's excellent [Pull Request guides](https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/). Note that sending your own PR will give you a faster resolution than the below options.

If you can't send a PR, that's all good, we understand! A member of the Octopus team will take a look at your issue and make sure that we get a fix merged as soon as convenient. 
**Please note** that it might take a bit longer to get a fix out there depending on what step template and what the bug is as it might require some setup to replicate the bug.

Please provide the following information when submitting an issue.

_Before submitting your issue, please delete everything above the line below._

---

### Step template
SSRS

### Step template parameter inputs
_Please show us how you have configured your step template, to make it easier for us to replicate the issue (screenshots is OK)_

### Step template version
We downloaded the version about a year ago and customized it for our need.

### Step template related environment information
_If the step template is for a specific software/hardware, please provide as much information about the software/hardware as possible to make it easy for us to replicate the issue_

### Octopus Server version
2019.6.7 LTS

### Expected behavior

SSRS should be able to deploy Shared Data set with XML datasource, as it does with SQL database as data source.

### Actual behavior

Exception calling "LoadReportDefinition" with "2" argument(s): "The dataset `TitleParametersDataset' refers to the
data source "Reporting.ReportingService_1_0", which does not exist."
At D:\Octopus\johnoctp02-wp3\Work\20191107144933-79784-697\Script.ps1:353 char:5
   $ExecutionInfo = $ReportExecutionProxy.LoadReportDefinition($Repo ...

[SSRSTemplate.txt](https://github.com/OctopusDeploy/Library/files/3825536/SSRSTemplate.txt)
[SSRS SetupOctopus.docx](https://github.com/OctopusDeploy/Library/files/3825555/SSRS.SetupOctopus.docx)

DataSource: Name: Reporting.ReportingService_1_0
DataSet Name: TitleParametersDataset

### Possible solution
_If you might have an idea of what the issue is, please let us know_

### Steps to reproduce the problem (for bugs)

_If there are specific steps that you took when you encountered the bug, please list them here_

**Comment by DevOpsDerek** [comment]
Closing Issue as no update in a year
