### ISSUE TITLE
Chain Deployment creates to many tasks when tenant names are alike

### ISSUE THREAD

**Issue by BastiaanMolsbeck** [OctopusDeploy/Library#833]
### Step template
Chain Deployment

### Step template parameter inputs
Several, but "Tenants" is the problematic one.

### Step template version
17

### Step template related environment information
Not relevant.

### Octopus Server version
v2019.9.8 LTS

### Expected behavior
When a Chain Deployment is executed for a tenanted process, it passes the tenant name as a variable, which will create a new task for this tenant.

### Actual behavior
But the Chain Deployment creates a new task for each tenant for which the name matches OR STARTS with the tenant name. This is not desired. Only one task should be created: just for the tenant which name matches the passed name exactly.
I'm not sure if this is only the case when the tenant name contains a space, but this is our scenario:
One tenant with name "ABC" and one with name "ABC TEST". When the main process executes the Chain Deployment, two tasks are created: one for tenant ABC and one for tenant ABC TEST.

### Possible solution
My guess is that the tenant is now determined by a filter instead of an exact match? This seems not right. But to be backwards-compatible a setting could be introduced to set this matching logic for a step?

### Steps to reproduce the problem (for bugs)
1. Create a tenant with name "ABC"
2. Create a tenant with name "ABC TEST"
3. Run a tenanted deployment just for tenant "ABC" of a process that contains a tenanted Chain Deployment. The Chain Deployment creates a task for both tenants, instead of just for tenant "ABC".

**Comment by DevOpsDerek** [comment]
Closing Issue as no update in a year
