### ISSUE TITLE
Delete azure-switch-staging-deployment-slot step template

### ISSUE THREAD

**Issue by justinjstark** [OctopusDeploy/Library#835]
### Step template
azure-switch-staging-deployment-slot

### Expected behavior
Runs a Switch-AzureRmWebAppSlot command in Azure.

### Actual behavior
This script does its own health checks prior to Switch-AzureRmWebAppSlot. The health checks are broken due to variable scoping issues (setting default values inside a function scope does not change the value of the variables in the script scope).

### Possible solution
Delete this step template. It is broken and leads to confusion. Switch-AzureRmWebAppSlot already does its own health checks to wait for the app to restart. This whole step template could be replaced with a simple wrapper around Switch-AzureRmWebAppSlot.

**Comment by DevOpsDerek** [comment]
Closing Issue as no update in a year
