### ISSUE TITLE
Application Insights - Annotate Release Fails because of incorrect TLS-config

### ISSUE THREAD

**Issue by petteas** [OctopusDeploy/Library#841]
Ref: https://github.com/microsoft/ApplicationInsights-Home/pull/386

### Step template
Application Insights - Annotate Release

### Step template parameter inputs
All the correct parameters

### Step template version
Latest

### Step template related environment information
--

### Octopus Server version
2019.8.6

### Expected behavior
For it to call annotate-release API

### Actual behavior

It fails with error:
```Failed to create an annotation with Id: ..... Error Exception, Description: The underlying connection was closed: An unexpected error occurred on a send..```

### Possible solution
Add ```[System.Net.ServicePointManager]::SecurityProtocol = 'Tls, Tls11, Tls12'``` before making the call to the API

### Steps to reproduce the problem (for bugs)
Run it

**Comment by hnrkndrssn** [comment]
Hi @petteas,

Thanks for reporting this issue, would you be interested in submitting a PR adding the necessary line of code to enable the correct security protocols? If not, that's Ok and I can get to it sometime in the next couple of days.

Cheers,
Henrik

**Comment by petteas** [comment]
Hi @hnrkndrssn 
I am happy to wait! Would be a nice christmas present :) 
Thanks for the fast reply

Best regards,
Petter

**Comment by petteas** [comment]
Thanks @hnrkndrssn 👏

**Comment by hnrkndrssn** [comment]
You're welcome @petteas!

Happy holidays 🎄
