### ISSUE TITLE
Latest App Insights: Annotate Release Failing

### ISSUE THREAD

**Issue by altnp** [OctopusDeploy/Library#844]
### Step template
Application Insights - Annotate Release

### Step template version
7

### Step template related environment information
None

### Octopus Server version
2019.10.12

### Expected behavior

Script should execute and annotate the release.

### Actual behavior
```
OperationStopped: Failed to create an annotation with Id: ... . Error Exception, Description: The underlying connection was closed: An unexpected error occurred on a receive.. 

At C:\Octopus\Work\20200106192330-60093-98\Script.ps1:135 char:3 
January 6th 2020 14:23:38Error
+      throw $output 
January 6th 2020 14:23:38Error
+      ~~~~~~~~~~~~~ 
January 6th 2020 14:23:38Error
at <ScriptBlock>, C:\Octopus\Work\20200106192330-60093-98\Script.ps1: line 135 
January 6th 2020 14:23:38Error
at <ScriptBlock>, C:\Octopus\Work\20200106192330-60093-98\Bootstrap.Script.ps1: line 2239 
January 6th 2020 14:23:38Error
at <ScriptBlock>, <No file>: line 1 
January 6th 2020 14:23:38Error
at <ScriptBlock>, <No file>: line 1 
January 6th 2020 14:23:38Fatal
The remote script failed with exit code 1 
January 6th 2020 14:23:38Fatal
The action Annotate Release on the Octopus Server failed 
```
### Possible solution
--

### Steps to reproduce the problem (for bugs)

--

**Comment by russellhorton** [comment]
Also seeing this issue - I'm using the latest version of the template with the security protocols enabled.

**Comment by Daniel-Svensson** [comment]
Same problem here.
running the script from https://raw.githubusercontent.com/microsoft/ApplicationInsights-Home/master/API/CreateReleaseAnnotation.ps1 works on the same machine

**Comment by richardwhatever** [comment]
anyone get a fix for this?

**Comment by harrisonmeister** [comment]
This could be linked to requiring TLS 1.2

**Comment by harrisonmeister** [comment]
The Script has this at the top :

```
$protocols = [Enum]::GetNames([System.Net.SecurityProtocolType])
if([Enum]::IsDefined([System.Net.SecurityProtocolType], 0)) {
    $protocols = @([System.Net.SecurityProtocolType]::SystemDefault)
}
Write-Output "Enabling security protocols: $protocols"
[System.Net.ServicePointManager]::SecurityProtocol = $protocols
```

What are your System Defaults for TLS?

**Comment by altnp** [comment]
I was using workers provided by Octopus Cloud, to “fix” this I had to setup my own worker and change the server default TLS versions (.net settings).

**Comment by harrisonmeister** [comment]
Hi @altnp - thanks for the info. I'll get a change sorted to set the TLS settings to 1.2 on this step template next week.

**Comment by harrisonmeister** [comment]
Raised #902 to force TLS 1.2 - changes will be reviewed next week.

**Comment by richardwhatever** [comment]
Thanks @harrisonmeister - I appreciate the swift response!
