### ISSUE TITLE
Slack detailed notification: Use of "username" variable leads to clashes

### ISSUE THREAD

**Issue by markhatton-axs** [OctopusDeploy/Library#855]
### Step template
Slack - Detailed Notification

### Step template parameter inputs
Standard, unremarkable setup - not really relevant to this issue.

### Step template version
6

### Step template related environment information
N/A

### Octopus Server version
v2019.9.10 LTS

### Expected behavior

Slack notification generated with a "username" (The username shown in Slack against these notifications), 

### Actual behavior

Slack notification generated with a "username" of whatever value it is set to in the process in which the step template is installed.

### Possible solution
Using "Username" as the variable name inside the step template would appear to be a sub-optimal choice as this variable name is commonly used inside deployment processes for application-level configuration. 

A possible solution would be to change the name of the variable used by the step template to make it less likely to clash with a variable in use in a deployment process. Perhaps something like "SlackDetailedUsername" rather than just "Username".

This would also be in line with Octopus's own [contribution guidelines for step templates](https://github.com/OctopusDeploy/Library/blob/master/.github/CONTRIBUTING.md), as this general issue [has apparently come up before](https://github.com/OctopusDeploy/Library/issues/556).

### Steps to reproduce the problem (for bugs)

1. Include the _Slack - Detailed Notification_ step template in to a deployment process, and configure it with a specific 
2. Set up a deployment process, with a variable defined with the name "Username" (I think it can be any type of variable that will come in to scope as part of the deployment).
3. Observe that the Slack notification appears with the "user" as the value of the variable in the project, rather than the username defined in the step template parameters.

**Comment by ryanrousseau** [comment]
This is a problem with older step templates. It's also why we require new templates to prefix their parameters.

Unfortunately, we can't change the old ones without causing issues for consumers. The best workaround for this is to make a copy of the step template in your instance and add the prefixes to that copy.

We also recommend prefixing your project variables if possible to avoid any potential name collisions.
