### ISSUE TITLE
run-octopus-runbook.json - Deadlock - Run.Runbook.Waitforfinish=True - hanging potentially forever

### ISSUE THREAD

**Issue by schrufygroovy** [OctopusDeploy/Library#892]
### Setup:
- $OctopusParameters[\"Run.Runbook.Waitforfinish\"] is true
- RunBook, that is executed, has some step (e.g: NuGet Checkout) with some condition like
`Waiting for the script in task ServerTasks-69270 to finish as that script requires that no other Octopus scripts are executing on this target at the same time.`

### Problem:
- The step is triggering the run book
- The step is waiting for the run book to finish
- The run book is started
- The run book hits a step where it shall be the only execution on the machine
- The run book step is waiting until it is the only execution

So we have deadlock here. How is the best approach to resolve this problem?

**Comment by OctopusBob** [comment]
Versions 4/5 introduced cancellation logic.  The default timeout is 30 minutes.  

Are you running the parent runbook on targets or workers?  I'd recommend running the run a runbook step on a worker as that shouldn't create a mutex.

**Comment by schrufygroovy** [comment]
@OctopusBob thx I will check this out

**Comment by schrufygroovy** [comment]
@OctopusBob  awesome 👍  works like a charm! thx a lot
