### ISSUE TITLE
IIS Website Create Step Template - SSL Binding Issue

### ISSUE THREAD

**Issue by jonsamwell** [OctopusDeploy/Library#99]
Hi,

It seems a invalid variable has crept into this template that causes it to fail to create an SSL binding in certain scenarios.

This below line uses a variable that is never initialized or assigned to ($ipAddress).  I think it is just a typo and should in fact be using this variable '$bindingIpAddress'.

```
$sslBindingsPath = (\"IIS:\\SslBindings\\\" + $ipAddress + \"!\" + $port)
```

Let me know if you want a pull request for this one.

Awesome product by the way!

Thanks,

Jon

**Comment by ChRonX13** [comment]
Ran into the exact same issue (after few hours of scratching my head at weird error messages). Modification of the variable to point to `$bindingIpAddress` allows the SSL functionality to work correctly.

**Comment by alfhenrik** [comment]
This has been fixed

**Comment by jonsamwell** [comment]
Awesome!
